### ISSUE TITLE
Love ur work

### ISSUE THREAD

**Issue by raulpuric** [Jakobovski/decoupled-multimodal-learning#1]
Not an issue, but I've been a silent fan of this repo for a while. Finally gave it a use.

Keep up the dope work. I'd give it more stars if I could.

**Comment by Jakobovski** [comment]
Hi Rual thanks for the feedback. 

What do you mean "Finally gave it a use"?

**Comment by Jakobovski** [comment]
email me at zohar.jackson@gmail.com. Cheers.
