### ISSUE TITLE
Trying to generate encodings

### ISSUE THREAD

**Issue by rupert0** [Jakobovski/decoupled-multimodal-learning#3]
Hi,

When I run 
```
$ python utils/fsdd_encoding_generator.py
$ python utils/mnist_encoding_generator.py
```

I get the following.

```
Traceback (most recent call last):
  File "utils/fsdd_encoding_generator.py", line 1, in <module>
    from utils.fsdd import FSDD
  File "~/dev/decoupled-multimodal-learning/utils/utils.py", line 6, in <module>
    from cdzproject import db, config
ImportError: No module named cdzproject
```

I'm using Python 3.6.6, just wondering if I'm missing something from the README or just something with project. 

My 1st issue was with the FSDD class, fixed the module name and everything worked. 
```
 % git diff utils/fsdd_encoding_generator.py
diff --git a/utils/fsdd_encoding_generator.py b/utils/fsdd_encoding_generator.py
index 183dc00..e4e3fc5 100644
--- a/utils/fsdd_encoding_generator.py
+++ b/utils/fsdd_encoding_generator.py
@@ -1,4 +1,4 @@
-from free_spoken_digit_dataset.utils.fsdd import FSDD
+from utils.fsdd import FSDD

```

**Comment by Jakobovski** [comment]
Hi rupert0,

- Python 3 is not supported, it might work but you should probably setup a virtualenv with python 2.7

- rename `~/dev/decoupled-multimodal-learning` to `~/dev/cdzproject`
- add `~/dev` to your python path 
- fsdd is not in utils, you will need to install it separately. Did you add it to the utils folder?

**Comment by Jakobovski** [comment]
I have updated the readme. Take a look at the bottom.

**Comment by rupert0** [comment]
Thanks for the information 

I will take a look at it 

:)
